GNUAPL: Quad_GTK Class Reference
Quad_GTK Class Reference
The class implementing ⎕GTK.
#include <Quad_GTK.hh>
Classes
struct window_entry
the context for a GTL window
Public Member Functions
Quad_GTK ()
Constructor.
void clear ()
close all open windows
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B)
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function * get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function * get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void get_attributes (int mode, Cell *dest) const
store the attributes (as per ⎕AT) of symbol at dest, ...
virtual UserFunction * get_ufun1 ()
return a pointer to this UserFunction (if it is one)
virtual const UserFunction * get_ufun1 () const
return a pointer to this UserFunction (if it is one)
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token ()
set tok to a Token for this function.
virtual Token eval_ ()
plain function, 0 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B)
monadic operator, 2 arguments
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B)
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B)
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B)
dyadic operator, 2 arguments, with axis
virtual Token eval_LB (Token &LO, Value_P B)
monadic operator, 1 argument
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B)
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B)
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B)
dyadic operator, 1 arguments, with axis
virtual Token eval_identity_fun (Value_P B, Axis axis)
Evaluate the identity function.
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X ()
return axis (non-0 only for derived functions)
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual Value_P get_value ()
return the variable value for this Id (if any) or 0 if this Id does not (currently) represent a variable.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_nc () const
Get current NameClass of this name.
Static Public Attributes
static Quad_GTK * fun = &Quad_GTK::_fun
Built-in function.
static Quad_GTK _fun
Built-in function.
Protected Types
enum Gtype {
gtype_V = 0,
gtype_S = 1,
gtype_I = 2,
gtype_F = 3
}
the type of a function parameter or return value
enum Fnum {
FNUM_INVALID = -1,
FNUM_0 = 0,
FNUM_GtkEntry_set_text,
FNUM_GtkEntry_get_text,
FNUM_GtkLabel_set_label,
FNUM_GtkProgressBar_set_fraction,
FNUM_GtkProgressBar_get_fraction,
FNUM_GtkLevelBar_set_value,
FNUM_GtkLevelBar_get_value,
FNUM_GtkComboBox_set_active,
FNUM_GtkComboBox_get_active,
FNUM_GtkDrawingArea_draw_commands,
FNUM_GtkDrawingArea_set_area_size,
FNUM_GtkDrawingArea_set_Y_origin,
FNUM_GtkComboBoxText_get_active_text,
FNUM_GtkSpinButton_get_value,
FNUM_GtkSpinButton_get_value_as_int
}
GTK function numbers: 1, 2, ...
enum Gtk_Command_Tag {
Command_0 = 1000,
Command_GtkEntry_set_text,
Command_GtkEntry_get_text,
Command_GtkLabel_set_label,
Command_GtkProgressBar_set_fraction,
Command_GtkProgressBar_get_fraction,
Command_GtkLevelBar_set_value,
Command_GtkLevelBar_get_value,
Command_GtkComboBox_set_active,
Command_GtkComboBox_get_active,
Command_GtkDrawingArea_draw_commands,
Command_GtkDrawingArea_set_area_size,
Command_GtkDrawingArea_set_Y_origin,
Command_GtkComboBoxText_get_active_text,
Command_GtkSpinButton_get_value,
Command_GtkSpinButton_get_value_as_int
}
Rx tags (commands) for function numbers: 1001, 1002, ...
enum Gtk_Response_Tag {
Response_0 = 2000,
Response_GtkEntry_set_text,
Response_GtkEntry_get_text,
Response_GtkLabel_set_label,
Response_GtkProgressBar_set_fraction,
Response_GtkProgressBar_get_fraction,
Response_GtkLevelBar_set_value,
Response_GtkLevelBar_get_value,
Response_GtkComboBox_set_active,
Response_GtkComboBox_get_active,
Response_GtkDrawingArea_draw_commands,
Response_GtkDrawingArea_set_area_size,
Response_GtkDrawingArea_set_Y_origin,
Response_GtkComboBoxText_get_active_text,
Response_GtkSpinButton_get_value,
Response_GtkSpinButton_get_value_as_int
}
Tx tags (command responses) for function numbers: 2001, 2002, ...
enum Event_tag {
Event_widget_fun = 3000,
Event_widget_fun_id_class,
Event_toplevel_window_done
}
tags specifying events
Protected Member Functions
Token eval_AB (Value_P A, Value_P B)
overloaded Function::eval_AB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B)
overloaded Function::eval_AXB()
Token eval_B (Value_P B)
overloaded Function::eval_B()
virtual Token eval_XB (Value_P X, Value_P B)
overloaded Function::eval_XB()
int resolve_window (const Value *X, UTF8_string &window_id)
X is supposed to be something like 4,"win_id". Store win_id in window_id and return the window number (4 in this example)
Fnum resolve_fun_name (UTF8_string &window_id, const Value *B)
B is a function name (-suffix).
int write_TL0 (int fd, int tag)
write a TLV with an empty V (thus L=0)
int write_TLV (int fd, int tag, const UTF8_string &value)
write a TLV
int open_window (const UCS_string &gui_filename, const UCS_string *css_filename)
open the GTH window described by gui_filename and optional css_filename
Value_P window_list () const
return the handles of currently open windows
Value_P close_window (int fd)
close the window with file descriptor fd
void poll_all ()
poll all fds and insert events into event_queue until no more events are pending
Value_P poll_response (int fd, int tag)
poll for a TLV on fd with a specific (reponse-) tag
Value_P read_fd (int fd, int tag)
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B)
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Protected Attributes
std::vector< window_entry > open_windows
the currently open GTK windows
UCS_string_vector event_queue
event queue for events from the GTK windows
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Additional Inherited Members
Public Types inherited from Function
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Detailed Description
The class implementing ⎕GTK.
Definition at line 32 of file Quad_GTK.hh.
Member Enumeration Documentation
Event_tag
enum Quad_GTK::Event_tag protected
tags specifying events
Enumerator
Event_widget_fun
H:widget:callback.
Event_widget_fun_id_class
H:widget:callback:glade_id:name.
Event_toplevel_window_done
H:Done.
Definition at line 34 of file Quad_GTK.hh.
Gtype
enum Quad_GTK::Gtype protected
the type of a function parameter or return value
Enumerator
gtype_V
void
gtype_S
string
gtype_I
integer
gtype_F
float
Definition at line 48 of file Quad_GTK.hh.
Member Function Documentation
read_fd()
Value_P Quad_GTK::read_fd (int fd, int tag) protected
read a TLV with a given tag (or any TLV if tag == -1) on a fd that is ready for reading. If the TLV is an event (i.e. unexpected) then insert it into event_queue and return 0; otherwise the TLV is a response that is returned.
Definition at line 307 of file Quad_GTK.cc.
References event_queue, Event_toplevel_window_done, Event_widget_fun, Event_widget_fun_id_class, and UCS_string::size().
Referenced by poll_all(), and poll_response().
The documentation for this class was generated from the following files:
src/Quad_GTK.hh
src/Quad_GTK.cc