GNUAPL: Prefix Class Reference
Prefix Class Reference
a class for reducing all statements of an Executable
#include <Prefix.hh>
Classes
struct Phrase
one phrase in the phrase table
Public Types
enum {
MAX_CONTENT = 10*MAX_REDUCTION_LEN,
MAX_CONTENT_1 = MAX_CONTENT - 1
}
max. number of lookahead token
Public Member Functions
Prefix (StateIndicator &_si, const Token_string &_body)
constructor
void clean_up ()
destructor
bool uses_function (const UserFunction *ufun) const
return true if ufun is on the stack
void print (ostream &out, int indent) const
print the state of this parser
void syntax_error (const char *loc)
throw an E_LEFT_SYNTAX_ERROR or an E_SYNTAX_ERROR
void lock_values (bool lock)
prevent or allow erase() of values on vstacks
void unmark_all_values () const
clear the mark flag of all values in this Prefix
int show_owners (const char *prfx, ostream &out, const Value &value) const
print all owners of value
Function_PC get_range_high () const
highest PC in current statement
Function_PC get_range_low () const
lowest PC in current statement
bool value_expected ()
lookahead is a complete index. return true if it belongs to a value and is not a function axis.
void print_range (ostream &out) const
print the current range (PC from - PC to) on out
bool replace_AB (Value_P old_value, Value_P new_value)
replace the left or right argument of a function (for retry) and return true on success
Token * locate_L ()
return the left argument of a failed primitive function (if any)
const Value_P * locate_X ()
return the axis argument of a failed primitive function (if any)
Token * locate_R ()
return the right argument of a failed primitive function (if any)
const Function * get_dyadic_fun () const
return the current monadic function (if any)
const Function * get_monadic_fun () const
return the current dyadic function (if any)
Token reduce_statements ()
execute one context (user defined function or operator, execute, or immediate execution)
int size () const
return the number of token currently in the FIFO
const Token & _at0 () const
return the leftmost token (e.g. A in A←B)
const Token & at0 () const
return the leftmost token (e.g. A in A←B)
Token & at0 ()
return the leftmost token (e.g. A in A←B)
const Token & at1 () const
return the second token from the left (e.g. ← in A←B)
Token & at1 ()
return the second token from the left (e.g. ← in A←B)
Token & at2 ()
return the third token from the left (e.g. B in A←B)
Token & at3 ()
return the fourth token from the left (e.g. B in A+/B)
bool dont_reduce (TokenClass next) const
return true if the next token binds stronger than the best match
Assign_state get_assign_state () const
return the current assignment state
void set_assign_state (Assign_state new_state)
set the current assignment state
Function_PC get_lookahead_high () const
return the highest PC seen in the current statement
Token_loc lookahead ()
read one more token (don't store yet)
void push (const Token_loc &tl)
store one more token
void pop_args_push_result (const Token &result)
pop prefix_len items and push result
Token_loc & pop ()
remove the leftmost token (e,g, A in A←B) from the stack and return it
void pop_and_discard ()
discard the leftmost token (e,g, A in A←B) from the stack
int vector_ass_count () const
the number of TOK_LSYMB2 tokens ahead (excluding the leftmost one already read into content)
void reset (const char *loc)
reset statement to empty state (e.g. after →N)
void print_stack (ostream &out, const char *loc) const
print the current stack
void set_PC (Function_PC new_pc)
set a new PC
Function_PC get_PC () const
return the current PC
Function_PC get_error_PC () const
return the PC that has caused an error
void set_action (R_action ra)
set the prefix parser action
void set_action (const Token &result)
set the prefix parser action according to (result-) Token type
bool is_value_bracket () const
read and resolve the token class left of [ ... ], PC is at ]
bool is_value_parenthesis (int pc) const
read and resolve the token class left of)
Token_loc & tos ()
return the leftmost (top-of-stack) Token_loc (at put position)
Token_loc & at (int idx)
return the idx'th Token_loc (from put position)
const Token_loc & at (int idx) const
return the idx'th Token_loc (from put position)
Protected Types
enum {
PHRASE_COUNT = 65,
PHRASE_MODU = 415,
MAX_PHRASE_LEN = 4
}
Protected Member Functions
void reduce____ ()
reduce phrase
void reduce_LPAR_B_RPAR_ ()
reduce phrase LPAR B RPAR
void reduce_LPAR_F_C_RPAR ()
reduce phrase LPAR F C RPAR
void reduce_N___ ()
reduce phrase N
void reduce_MISC_F_B_ ()
reduce phrase ASS F B
void reduce_MISC_F_C_B ()
reduce phrase ASS F C B
void reduce_A_F_B_ ()
reduce phrase A F B
void reduce_A_M_B_ ()
reduce phrase A M B
void reduce_A_F_C_B ()
reduce phrase A F C B
void reduce_A_M_C_B ()
reduce phrase A M C B
void reduce_F_M__ ()
reduce phrase F M
void reduce_F_M_C_ ()
reduce phrase F M C
void reduce_F_C_M_ ()
reduce phrase F C M
void reduce_F_C_M_C ()
reduce phrase F C M C
void reduce_A_M__ ()
reduce phrase A M
void reduce_D_V__ ()
reduce phrase D V
void reduce_F_D_B_ ()
reduce phrase F D B
void reduce_F_D_G_ ()
reduce phrase F D G
void reduce_F_D_C_B ()
reduce phrase F D C B
void reduce_A_C__ ()
reduce phrase A C
void reduce_V_C__ ()
reduce phrase V C
void reduce_V_C_ASS_B ()
reduce phrase V C ASS B
void reduce_F_V__ ()
reduce phrase F V
void reduce_A_ASS_B_ ()
reduce phrase A ASS B
void reduce_V_ASS_B_ ()
reduce phrase V ASS B
void reduce_D_V_ASS_B ()
reduce phrase D V ASS B
void reduce_V_ASS_F_ ()
reduce phrase V ASS F
void reduce_RBRA___ ()
reduce phrase RBRA
void reduce_LBRA_I__ ()
reduce phrase LBRA I
void reduce_LBRA_B_I_ ()
reduce phrase LBRA B I
void reduce_A_B__ ()
reduce phrase A B
void reduce_V_RPAR_ASS_B ()
reduce phrase V RPAR ASS B
void reduce_END_VOID__ ()
reduce phrase END VOID
void reduce_END_B__ ()
reduce phrase END B
void reduce_END_GOTO__ ()
reduce phrase END GOTO
void reduce_END_GOTO_B_ ()
reduce phrase END GOTO B
void reduce_END_A_GOTO_B ()
reduce phrase END A GOTO B
void reduce_RETC___ ()
reduce phrase RETC
void reduce_RETC_VOID__ ()
reduce phrase RETC VOID
void reduce_RETC_B__ ()
reduce phrase RETC B
void reduce_RETC_GOTO__ ()
reduce phrase RETC GOTO
void reduce_RETC_GOTO_B_ ()
reduce phrase RETC GOTO B
void reduce_RETC_A_GOTO_B ()
reduce phrase RETC A GOTO B
Protected Attributes
const uint64_t instance
a unique identifier
StateIndicator & si
the StateIndicator that contains this parser
int put
put pointer (for the next token at PC)
Token_loc content [MAX_CONTENT]
the lookahead tokens (tokens that were read but not yet reduced)
Token_loc saved_lookahead
the X token (leftmost token in MISC phrase, if any)
const Token_string & body
the function body. This parser parses tokens body[pc_from] ...
Function_PC PC
the current pc (+1)
Assign_state assign_state
assignment state
Function_PC lookahead_high
the highest PC seen in the current statement
int prefix_len
length of matched prefix (before calling a reduce_XXX() function)
R_action action
the action to be taken after returning from a reduce_XXX() function
const Phrase * best
the phrase being reduced (only valid if a phrase was matched)
Static Protected Attributes
static const Phrase hash_table [PHRASE_MODU]
a hash table with all valid phrases (and many invalid entries)
static uint64_t instance_counter = 0
a generator for unique identifiers
Friends
class XML_Loading_Archive
class XML_Saving_Archive
Detailed Description
a class for reducing all statements of an Executable
Definition at line 57 of file Prefix.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
PHRASE_COUNT
number of phrases
PHRASE_MODU
hash table size
Definition at line 123 of file Prefix.hh.
Member Function Documentation
reduce_V_RPAR_ASS_B()
void Prefix::reduce_V_RPAR_ASS_B () protected
reduce phrase V RPAR ASS B
pattern V) ← B
Definition at line 1885 of file Prefix.cc.
References action, at0(), at3(), body, Token::get_apl_val(), Token::get_Class(), Token::get_sym_ptr(), Token::get_tag(), lookahead(), Token::move_1(), PC, pop_args_push_result(), prefix_len, Symbol::resolve_lv(), set_assign_state(), syntax_error(), Token_loc::tok, vector_ass_count(), and Symbol::vector_assignment().
The documentation for this class was generated from the following files:
src/Prefix.hh
src/Prefix.cc