GNUAPL: Quad_TF Class Reference
Quad_TF Class Reference
The class implementing ⎕TF.
#include <Quad_TF.hh>
Public Member Functions
Quad_TF ()
Constructor.
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB().
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual UserFunction * get_ufun1 ()
return a pointer to this UserFunction (if it is one)
virtual const UserFunction * get_ufun1 () const
return a pointer to this UserFunction (if it is one)
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_identity_fun (Value_P B, Axis axis) const
Evaluate the identity function.
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual const Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual ShapeItem string_to_int (const UCS_string &name) const
return a (pseudo-) axis for name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual Value_P get_value ()
return the variable value for this Id (if any) or 0 if this Id does not (currently) represent a variable.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_nc () const
Get current NameClass of this name.
Static Public Member Functions
static bool is_inverse (const UCS_string &maybe_name)
return true if val contains an 1⎕TF or 2⎕TF record
static Value_P tf1 (const UCS_string &symbol_name)
return B in transfer format 1 (old APL format)
static Token tf2 (const UCS_string &symbol_name)
return B in transfer format 2 (new APL2 format)
static Value_P tf3 (const UCS_string &symbol_name)
return B in transfer format 3 (APL2 CDR format)
static void tf2_value (int level, UCS_string &ucs, const Value &value, ShapeItem nesting)
append ravel of value in tf2_format to ucs. Return true iff the value should be enclosed in parentheses when grouped.
static void tf2_fun_ucs (UCS_string &ucs, const UCS_string &fun_name, const Function &fun)
store B in transfer format 2 (new APL format) into ucs
static void tf2_char_vec (UCS_string &ucs, const UCS_string &vec)
store simple character vector vec in ucs, either as 'xxx' or as (UCS nn nnn ...)
static UCS_string no_UCS (const UCS_string &ucs)
undo ⎕UCS() created by tf2_char_vec
static UCS_string tf2_inverse (const UCS_string &ravel)
try inverse ⎕TF2 of ucs, set new_var_or_fun if successful
static Token tf2_var (const UCS_string &var_name, Value_P val)
return B in transfer format 2 (new APL format) for a variable
Static Public Attributes
static Quad_TF * fun = &Quad_TF::_fun
Built-in function.
static Quad_TF _fun
Built-in function.
Static Protected Member Functions
static void tf2_shape (UCS_string &ucs, const Shape &shape, ShapeItem nesting)
append shape in tf2_format to ucs.
static void tf2_ravel (int level, UCS_string &ucs, const ShapeItem len, const Cell *cells)
append ravel cells in tf2_format to ucs.
static void tf2_all_char_ravel (int level, UCS_string &ucs, const Value &value)
append the ravel of a simple character array (of any rank)
static Value_P tf1 (const UCS_string &var_name, Value_P B)
return B in transfer format 1 (old APL format) for variable B
static Value_P tf1 (const UCS_string &fun_name, const Function &B)
return B in transfer format 1 (old APL format) for function B
static Value_P tf1_inv (const UCS_string &ravel)
return inverse transfer format 1 (old APL format) for a variable
static void tf2_reduce (Token_string &tos)
simplify tos by removing UCS nnn etc.
static bool tf2_reduce_ENCLOSE (Token_string &tos)
replace pattern ⊂ B in tos with the single token (⊂B); return true iff done so.
static bool tf2_reduce_RHO (Token_string &tos)
replace pattern A ⍴ B in tos with the single token (A⍴B); return true iff done so.
static bool tf2_reduce_sequence (Token_string &tos)
replace pattern N - ⎕IO - ⍳ K in tos with N N+1 ... N+K-1; return true iff done so.
static bool tf2_reduce_sequence1 (Token_string &tos)
replace pattern N - M × ⎕IO - ⍳ K in tos with M × (N N+1 ... N+K-1); return true iff done so.
static bool tf2_reduce_parentheses (Token_string &tos)
replace pattern (B) in tos with B; return true iff done so.
static bool tf2_glue (Token_string &tos)
replace pattern value1 value2... in tos with the single token
static bool tf2_reduce_COMMA (Token_string &tos)
replace pattern , B in tos with single token (,B); return true iff done so.
static UCS_string tf2_fun (const UCS_string &fun_name, const Function &fun)
return B in transfer format 2 (new APL format) for a function
static bool tf2_reduce_ENCLOSE_ENCLOSE (Token_string &tos)
replace pattern ⊂ ⊂ B in tos with the single token (⊂⊂B)
static bool tf2_reduce_ENCLOSE1 (Token_string &tos)
replace pattern ⊂ B in tos with the single token (⊂B)
static void tf2_reduce_UCS (Token_string &tos)
replace ⎕UCS n... with the corresponding Unicodes,
static ShapeItem tf2_toggle_UCS (Value &val)
in-place exchange of IntCells and CharCells
Additional Inherited Members
Public Types inherited from Function
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕TF.
The system function Quad-TF (Transfer Form).
Definition at line 29 of file Quad_TF.hh.
Member Function Documentation
tf2_var()
Token Quad_TF::tf2_var (const UCS_string & var_name, Value_P val) static
return B in transfer format 2 (new APL format) for a variable
the right hand side of VAR←VALUE
Definition at line 484 of file Quad_TF.cc.
References Cell::get_pointer_value(), Value_P_Base::getref(), Cell::is_pointer_cell(), UCS_string::size(), and tf2_value().
Referenced by tf2(), and Symbol::write_OUT().
The documentation for this class was generated from the following files:
src/Quad_TF.hh
src/Quad_TF.cc