GNUAPL: ScalarFunction Class Reference
ScalarFunction Class Reference abstract
Base class for all scalar functions.
#include <ScalarFunction.hh>
Public Member Functions
ScalarFunction (TokenTag tag, CellFunctionStatistics *stat_AB, CellFunctionStatistics *stat_B, ShapeItem thresh_AB, ShapeItem thresh_B)
Construct a ScalarFunction with Id id.
Token eval_scalar_B (Value_P B, prim_f1 fun) const
Evaluate a scalar function monadically.
Token eval_scalar_AB (Value_P A, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically.
virtual prim_f2 get_scalar_f2 () const =0
overloaded Function::get_scalar_f2
Token eval_scalar_AXB (Value_P A, Value_P X, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically with axis.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual UserFunction * get_ufun1 ()
return a pointer to this UserFunction (if it is one)
virtual const UserFunction * get_ufun1 () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_identity_fun (Value_P B, Axis axis) const
Evaluate the identity function.
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual const Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual ShapeItem string_to_int (const UCS_string &name) const
return a (pseudo-) axis for name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual Value_P get_value ()
return the variable value for this Id (if any) or 0 if this Id does not (currently) represent a variable.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_nc () const
Get current NameClass of this name.
Protected Member Functions
Value_P do_scalar_B (ErrorCode &ec, Value_P B, prim_f1 fun) const
compute the monadic scalar function fun along one ravel
Value_P do_scalar_AB (ErrorCode &ec, Value_P A, Value_P B, prim_f2 fun) const
compute the dyadic scalar function fun along one ravel
void expand_pointers (Value_P Z, Value &Z_owner, const Cell *cell_A, const Cell *cell_B, prim_f2 fun) const
Apply a function to a nested sub array.
Value_P eval_scalar_AXB (Value_P A, bool *axis_present, Value_P B, prim_f2 fun, bool reversed) const
A helper function for eval_scalar_AXB().
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Token eval_scalar_identity_fun (Value_P B, Axis axis, Value_P FI0)
Evaluate the identity function.
Static Protected Attributes
static Thread_context::PoolFunction PF_scalar_AB
parallel eval_scalar_AB
static Thread_context::PoolFunction PF_scalar_B
parallel eval_scalar_B
Additional Inherited Members
Public Types inherited from Function
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
Base class for all scalar functions.
Base class for scalar functions (functions whose monadic and/or dyadic version are scalar.
Definition at line 36 of file ScalarFunction.hh.
Member Function Documentation
eval_scalar_AXB()
Value_P ScalarFunction::eval_scalar_AXB (Value_P A, bool * axis_present, Value_P B, prim_f2 fun, bool reversed) const protected
A helper function for eval_scalar_AXB().
make A the value with the smaller rank).
Definition at line 871 of file ScalarFunction.cc.
References expand_pointers(), Value_P_Base::get(), Shape::get_shape_item(), Value_P_Base::getref(), and ArrayIterator::more().
The documentation for this class was generated from the following files:
src/ScalarFunction.hh
src/ScalarFunction.cc