GNUAPL: APL_Float_Base Class Reference
APL_Float_Base Class Reference
the essential data of an APL_Float, so that it can be used in a union
#include <APL_Float_as_class.hh>
Public Member Functions
double _get () const
return the value as double
APL_Float_Base & _set (double d)
set the value from a double
operator APL_Float () const
cast to APL_Float (creates a copy)
const APL_Float * pAPL_Float () const
up-cast const APL_Float_Base * to const APL_Float *
APL_Float * pAPL_Float ()
up-cast APL_Float_Base * to APL_Float *
operator double ()
cast to double
operator const APL_Integer () const
cast to APL_Integer
Protected Attributes
double dval
the value
Detailed Description
the essential data of an APL_Float, so that it can be used in a union
Definition at line 103 of file APL_Float_as_class.hh.
Member Function Documentation
operator APL_Float()
APL_Float_Base::operator APL_Float () const inline
cast to APL_Float (creates a copy)
cast from APL_Float_Base to APL_Float
Definition at line 161 of file APL_Float_as_class.hh.
References dval.
pAPL_Float() [1/2]
const APL_Float * APL_Float_Base::pAPL_Float () const inline
up-cast const APL_Float_Base * to const APL_Float *
up-cast from const APL_Float_Base * to const APL_Float *
Definition at line 168 of file APL_Float_as_class.hh.
Referenced by _set(), FloatCell::dfval(), and FloatCell::FloatCell().
pAPL_Float() [2/2]
APL_Float * APL_Float_Base::pAPL_Float () inline
up-cast APL_Float_Base * to APL_Float *
up-cast from APL_Float_Base * to APL_Float *
Definition at line 175 of file APL_Float_as_class.hh.
References _get().
The documentation for this class was generated from the following file:
src/APL_Float_as_class.hh