GNUAPL: NativeFunction Class Reference
NativeFunction Class Reference
A defined function written in C++.
#include <NativeFunction.hh>
Public Types
enum NativeCategory {
NCAT_F0,
NCAT_F12,
NCAT_OP1,
NCAT_OP2
}
kind of native function
Public Types inherited from Function
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions
const UCS_string & get_so_path () const
return the name of the .so library that implements this function
bool is_valid () const
return true if the .so library was successfully loaded
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual UserFunction * get_ufun1 ()
return a pointer to this UserFunction (if it is one)
virtual const UserFunction * get_ufun1 () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual const Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual ShapeItem string_to_int (const UCS_string &name) const
return a (pseudo-) axis for name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual Value_P get_value ()
return the variable value for this Id (if any) or 0 if this Id does not (currently) represent a variable.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_nc () const
Get current NameClass of this name.
Static Public Member Functions
static NativeFunction * fix (const UCS_string &so_name, const UCS_string &apl_name)
⎕FX a native funtion from a shared library (dlopen) handle
static void cleanup ()
close all shared libs
static UCS_string load_emacs_library (const char *emacs_arg)
load shared lib for emacs mode, return error info on failure
Protected Types
typedef Value_P Vr
shortcut for Value_P
typedef const Function & Fr
shortcut for const Function &
Protected Member Functions
NativeFunction (const UCS_string &so_name, const UCS_string &apl_name)
constructor (only fix() may call it)
~NativeFunction ()
destructor: close so_handle
virtual bool is_defined () const
overloaded Function::is_defined()
virtual bool is_native () const
overloaded Function::is_native()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool is_operator () const
overloaded Function::is_operator()
virtual void print_properties (ostream &out, int indent) const
Overloaded Function::print_properties()
virtual ostream & print (std::ostream &) const
Overloaded Function::print()
virtual UCS_string canonical (bool with_lines) const
Overloaded Function::canonical()
virtual Token eval_ () const
Overloaded Function::eval_()
virtual Token eval_B (Value_P B) const
Overloaded Function::eval_B()
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB()
virtual Token eval_LB (Token &LO, Value_P B) const
Overloaded Function::eval_LB()
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
Overloaded Function::eval_ALB()
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_LRB()
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_ALRB()
virtual Token eval_XB (Value_P X, Value_P B) const
Overloaded Function::eval_XB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
Overloaded Function::eval_AXB()
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_LXB()
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_ALXB()
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_LRXB()
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_ALRXB()
virtual Token eval_fill_B (Value_P B) const
Overloaded Function::eval_fill_B()
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Overloaded Function::eval_fill_AB()
virtual Token eval_identity_fun (Value_P B, Axis axis) const
Overloaded Function::eval_identity_fun()
virtual void destroy ()
Overloaded Function::destroy()
UCS_string get_name () const
return the name of the named object
Static Protected Member Functions
static void * open_so_file (UCS_string &t4, UCS_string &so_path)
open .so file in one of several directories. On success set handle and update so_path.
static void * try_one_file (const char *filename, UCS_string &t4)
try to open one .so file
Protected Attributes
void * handle
dl_open() handle of shared library
UCS_string name
APL name of the function.
UCS_string original_so_path
the right argument B of of A ⎕FX B before expanding it to a path
UCS_string so_path
library file path of the function
bool valid
true if the shared lib was successfully opened
Fun_signature signature
type of function (niladic / nomadic / moadic operator / dyadic operator)
Token(* f_eval_)(const NativeFunction *)
pointer to function eval_() in shared library
Token(* f_eval_B)(Vr B, const NativeFunction *)
pointer to function eval_B() in shared library
Token(* f_eval_AB)(Vr A, Vr B, const NativeFunction *)
pointer to function eval_AB() in shared library
Token(* f_eval_LB)(Fr LO, Vr B, const NativeFunction *)
pointer to function eval_LB() in shared library
Token(* f_eval_ALB)(Vr A, Fr LO, Vr B, const NativeFunction *)
pointer to function eval_ALB() in shared library
Token(* f_eval_LRB)(Fr LO, Fr RO, Vr B, const NativeFunction *)
pointer to function eval_LRB() in shared library
Token(* f_eval_ALRB)(Vr A, Fr LO, Fr RO, Vr B, const NativeFunction *)
pointer to function eval_ALRB() in shared library
Token(* f_eval_XB)(Vr X, Vr B, const NativeFunction *)
pointer to function eval_XB() in shared library
Token(* f_eval_AXB)(Vr A, Vr X, Vr B, const NativeFunction *)
pointer to function eval_AXB() in shared library
Token(* f_eval_LXB)(Fr LO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_LXB() in shared library
Token(* f_eval_ALXB)(Vr A, Fr LO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_() in shared library
Token(* f_eval_LRXB)(Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_LRXB() in shared library
Token(* f_eval_ALRXB)(Vr A, Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_ALRXB() in shared library
Token(* f_eval_fill_B)(Vr B, const NativeFunction *)
pointer to function eval_fill_B() in shared library
Token(* f_eval_fill_AB)(Vr A, Vr B, const NativeFunction *)
pointer to function eval_fill_AB() in shared library
Token(* f_eval_ident_Bx)(Vr B, Axis x, const NativeFunction *)
pointer to function eval_identity_fun() in shared library
bool(* close_fun)(Cause cause, const NativeFunction *caller)
callback before library is closed
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Static Protected Attributes
static std::vector< NativeFunction * > valid_functions
all native functions currently active
Additional Inherited Members
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Detailed Description
A defined function written in C++.
A defined function written in C++.
Definition at line 35 of file NativeFunction.hh.
Member Enumeration Documentation
NativeCategory
enum NativeFunction::NativeCategory
kind of native function
Enumerator
NCAT_F0
niladic function
NCAT_F12
nomadic (monadic or dyadic) function
NCAT_OP1
monadic operator
NCAT_OP2
dyadic operator
Definition at line 54 of file NativeFunction.hh.
Constructor & Destructor Documentation
NativeFunction()
NativeFunction::NativeFunction (const UCS_string & so_name, const UCS_string & apl_name) protected
constructor (only fix() may call it)
read function pointers...
Definition at line 35 of file NativeFunction.cc.
References Symbol::cant_be_defined(), close_fun, eval_(), eval_AB(), eval_ALB(), eval_ALRB(), eval_ALRXB(), eval_ALXB(), eval_AXB(), eval_B(), eval_fill_AB(), eval_fill_B(), eval_LB(), eval_LRB(), eval_LRXB(), eval_LXB(), eval_XB(), handle, is_operator(), Workspace::lookup_symbol(), Workspace::more_error(), open_so_file(), Symbol::set_nc(), signature, so_path, Function::tag, valid, and valid_functions.
Referenced by fix().
The documentation for this class was generated from the following files:
src/NativeFunction.hh
src/NativeFunction.cc