GNUAPL: UserPreferences Struct Reference
UserPreferences Struct Reference
Various preferences of the user (sorted alphabetically)
#include <UserPreferences.hh>
Public Member Functions
UserPreferences ()
void read_config_file (bool sys, bool log_startup)
read a preference file and update parameters set there
void read_threshold_file (bool sys, bool log_startup)
read a parallel_thresholds file and update parameters set there
bool parse_argv_1 ()
parse command line parameters (before reading preference files)
void parse_argv_2 (bool logit)
parse command line parameters (after reading preference files)
void expand_argv (int argc, const char **argv)
expand lumped arguments
Static Public Member Functions
static void usage (const char *prog)
print possible command line options and exit
static const char * is_default (bool yes)
return " (default)" if yes is true
static void show_configure_options ()
print how the interpreter was configured (via ./configure) and exit
static void show_GPL (ostream &out)
print the GPL
static void show_version (ostream &out)
show version information
Public Attributes
std::vector< const char * > original_argv
argv/argc at startup
std::vector< const char * > expanded_argv
argv/argc after expand_argv
bool append_summary
append test results to summary.log rather than overriding it
bool auto_OFF
true if the interpreter shall)OFF on EOF of the last input file
bool backup_before_save
backup on)SAVE
int control_Ds_to_exit
number of control-Ds to exit (0 = never)
int CPU_limit_secs
limit (seconds) on the CPU time
bool daemon
run as deamon
bool discard_indentation
true if leading spaces in the ∇-editor shall be dropped
bool disable_native_functions
disable dyadic ⎕FX
bool disable_Quad_FIO
disable ⎕FIO
bool disable_Quad_GTK
disable ⎕GTK
bool disable_Quad_PLOT
disable ⎕PLOT
bool disable_Quad_SQL
disable ⎕SQL
bool disable_SAVE_command
disable)SAVE and)DUMP cimmands
bool do_CONT
load workspace CONTINUE on start-up
bool do_Color
output coloring enabled
bool do_not_echo
true if no input echo is wanted.
bool echo_CIN
true to echo input (after editing)
const char * emacs_arg
an argument for emacs mode
bool emacs_mode
true if emacs mode is wanted
std::vector< const char * > eval_exprs
–eval expressions
int initial_pw
initial value of ⎕PW
UTF8_string initial_workspace
a workspace to be loaded at startup
UTF8_string latent_expression
something to be executed at startup (–LX)
int line_history_len
number of lines in the input line history
UTF8_string keyboard_layout_file
name of a user-provided keyboard layout file
UTF8_string line_history_path
location of the input line history
const char * mem_arg
argument of –mem (if any: 0 if not given, "" if given but empty)
bool multi_line_strings
true if old-style multi-line strings are allowed (in ∇-defined functions)
bool multi_line_strings_3
true if new-style multi-line strings are allowed
int nabla_to_history
when function body shall go into the history
bool output_to_cout
true if output shall go to cout, otherwise to cerr
bool randomize_testfiles
randomize the order of testfiles
bool raw_cin
send no ESC sequences on stderr
CoreCount requested_cc
desired core count
int requested_id
desired –id (⎕AI[1] and shared variable functions)
int requested_par
desired –par (⎕AI[1] and shared variable functions)
bool safe_mode
true if –safe command line option was given
size_t script_argc
the argument number of the APL script name (if run from a script) in expanded_argv, or 0 if apl is started directly.
timeval session_start
when apl was started
bool silent
true if no banner/Goodbye is wanted.
bool system_do_svars
true if shared variables are enabled by the system. This is initially the same as user_do_svars, but can become false if something goes wrong
int tcp_port
TCP port to be used (instead of stdin/stderr)
bool tcp_websocket
enable websocket protocol on the TCP port
bool user_do_svars
true if shared variables are wanted by the user
int user_profile
the profile to be used (in the preferences file)
int wait_ms
wait at start-up
bool WINCH_sets_pw
true if the WINCH signal shall modify ⎕PW
Protected Member Functions
FILE * open_user_file (const char *fname, char *opened_filename, bool sys, bool log_startup)
open a user-supplied config file (in $HOME or gnu-apl.d)
Static Protected Member Functions
static int decode_ASCII (const char *strg)
decode a byte in a preferences file. The byte can be given as ASCII name (currently only ESC is understood), a single char (that stands for itself), or 2 2-character hex value
static bool is_APL_script (const char *filename)
return true if file filename is an APL script (has execute permission and starts with #!
static void set_threshold (Function_P fun, int padic, int macn, ShapeItem threshold)
set the parallel threshold of function fun to threshold
Detailed Description
Various preferences of the user (sorted alphabetically)
a structure that contains user preferences from different sources (command line arguments, config files, environment variables ...)
Definition at line 37 of file UserPreferences.hh.
Constructor & Destructor Documentation
UserPreferences()
UserPreferences::UserPreferences () inline
definitions of facilities inside the GNU APL interpreter that can be disabled (by means of preference file entries) for security reasons
Definition at line 39 of file UserPreferences.hh.
References append_summary, auto_OFF, backup_before_save, control_Ds_to_exit, expanded_argv, is_default(), original_argv, parse_argv_1(), parse_argv_2(), read_config_file(), read_threshold_file(), session_start, show_configure_options(), show_GPL(), show_version(), and usage().
Member Function Documentation
expand_argv()
void UserPreferences::expand_argv (int argc, const char ** argv)
expand lumped arguments
GNU APL can be started in a number of ways:
directly - argc/argv have the usual meaning
as a script without arguments on the first script line, e.g. /usr/bin/apl SCRIPT.apl [ scriptargs... ]
as a script with arguments on the first script line, e.g. /usr/bin/apl 'line 1 arguments' SCRIPT.apl [ scriptargs... ]
On a non-GNU/linux OS; the semantics of the first script line is unknown.
To make this work, 2, should be avoided and 4. should use exactly one argument. The following first script lines shall work (assuming GNU APL lives in /usr/bin:
/usr/bin/apl – /usr/bin/apl -s /usr/bin/apl –script /usr/bin/apl -s – at least on GNU/linux /usr/bin/apl –script – at least on GNU/linux
expand_argv() does the following:
expand argv[1] into multiple arguments
maybe set script_argc
Definition at line 816 of file UserPreferences.cc.
References expanded_argv, is_APL_script(), original_argv, and script_argc.
Referenced by init_apl().
read_config_file()
void UserPreferences::read_config_file (bool sys, bool log_startup)
read a preference file and update parameters set there
definitions of facilities inside the GNU APL interpreter that can be disabled (by means of preference file entries) for security reasons
< disable dyadic ⎕FX
< disable ⎕FIO
< disable ⎕GTK
< disable ⎕PLOT
< disable ⎕SQL
< disable)SAVE and)DUMP cimmands
Definition at line 1077 of file UserPreferences.cc.
References UTF8_string::append_ASCII(), auto_OFF, backup_before_save, Output::clear_EOL, Output::clear_EOS, Output::color_CERR, Output::color_CERR_background, Output::color_CERR_foreground, Output::color_CIN, Output::color_CIN_background, Output::color_CIN_foreground, Output::color_COUT, Output::color_COUT_background, Output::color_COUT_foreground, Output::color_RESET, Output::color_UERR, Output::color_UERR_background, Output::color_UERR_foreground, control_Ds_to_exit, LibPaths::LibDir::CSRC_PREF_HOME, LibPaths::LibDir::CSRC_PREF_SYS, decode_ASCII(), discard_indentation, do_Color, Output::ESC_CursorDown, Output::ESC_CursorEnd, Output::ESC_CursorHome, Output::ESC_CursorLeft, Output::ESC_CursorRight, Output::ESC_CursorUp, Output::ESC_Delete, Output::ESC_InsertMode, initial_pw, keyboard_layout_file, line_history_len, line_history_path, mem_arg, multi_line_strings, multi_line_strings_3, nabla_to_history, open_user_file(), output_to_cout, LibPaths::set_lib_dir(), silent, system_do_svars, user_do_svars, user_profile, and WINCH_sets_pw.
Referenced by init_apl(), and UserPreferences().
usage()
void UserPreferences::usage (const char * prog) static
print possible command line options and exit
CYGWIN defines _B.
Definition at line 53 of file UserPreferences.cc.
Referenced by parse_argv_2(), and UserPreferences().
Member Data Documentation
disable_native_functions
bool UserPreferences::disable_native_functions
disable dyadic ⎕FX
definitions of facilities inside the GNU APL interpreter that can be disabled (by means of preference file entries) for security reasons
Definition at line 27 of file UserPreferences.hh.
The documentation for this struct was generated from the following files:
src/UserPreferences.hh
src/UserPreferences.cc